apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-todo-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/djblackett/k8s-todo-dep
    path: manifests/output/production.yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
