apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: broadcaster
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 100
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
      - name: todo-go-broadcaster
        image: PROJECT/BROADCASTER
        env:
        - name: ENVIRONMENT
          value: production
