resources:
- ../../base
- ./backup.yaml

patchesStrategicMerge:
- broadcaster.deployment.yaml


# namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: 5b2446b7cc0e43785e987a63de0714e09ffc1711
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: 5b2446b7cc0e43785e987a63de0714e09ffc1711
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: 5b2446b7cc0e43785e987a63de0714e09ffc1711

namespace: production
