resources:
- backup.yaml
- ../../base



namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: frontend.deployment.yaml
- path: backend.deployment.yaml
- path: broadcaster.deployment.yaml
# - path: backup.yaml
