resources:
- ../../base
- ./backup.yaml

patchesStrategicMerge:
- broadcaster.deployment.yaml


# namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: 857f090abd1f19c2cdb31bebd087361f7dfe14dd
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: 857f090abd1f19c2cdb31bebd087361f7dfe14dd
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: 857f090abd1f19c2cdb31bebd087361f7dfe14dd

namespace: production
