resources:
- ../../base
- ./backup.yaml

patchesStrategicMerge:
- broadcaster.deployment.yaml


# namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: e6f4b91e4159b574a12d40cf9e9e6ccc5680c7c3
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: e6f4b91e4159b574a12d40cf9e9e6ccc5680c7c3
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: e6f4b91e4159b574a12d40cf9e9e6ccc5680c7c3

namespace: production
