resources:
- ../../base
- ./backup.yaml

patchesStrategicMerge:
- broadcaster.deployment.yaml


# namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: a05fc663a45315e901f2d4144505a6ff4d236d43
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: a05fc663a45315e901f2d4144505a6ff4d236d43
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: a05fc663a45315e901f2d4144505a6ff4d236d43

namespace: production
