resources:
- ../../base
- ./backup.yaml

patchesStrategicMerge:
- broadcaster.deployment.yaml


# namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: f9c6f5e562906e5bcd45cf91689d39f9a67d15bc
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: f9c6f5e562906e5bcd45cf91689d39f9a67d15bc
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: f9c6f5e562906e5bcd45cf91689d39f9a67d15bc

namespace: production
