resources:
- ../../base
- ./backup.yaml

patchesStrategicMerge:
- broadcaster.deployment.yaml


# namePrefix: prod-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: c9f2868570d255dcf865734f5ee58c4c03a71848
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: c9f2868570d255dcf865734f5ee58c4c03a71848
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: c9f2868570d255dcf865734f5ee58c4c03a71848

namespace: production
