apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: broadcaster
spec:
  replicas: 6
  #  strategy:
  #    canary:
  #      steps:
  #        - setWeight: 100
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
      - name: todo-go-broadcaster
        image: PROJECT/BROADCASTER
        ports:
        - containerPort: 8500
        env:
        - name: PORT
          value: "8500"
        - name: NATS_URL
          value: my-nats.development.svc.cluster.local:4222
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: webhook-url
              key: WEBHOOK_URL
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        readinessProbe:
          initialDelaySeconds: 10 # Initial delay until the readiness is tested
          periodSeconds: 5 # How often to test
          httpGet:
            path: /healthz
            port: 8500
        livenessProbe:
          initialDelaySeconds: 20 # Initial delay until the liveness is tested
          periodSeconds: 5 # How often to test
          httpGet:
            path: /healthz
            port: 8500

---
apiVersion: v1
kind: Service
metadata:
  name: broadcaster-svc
spec:
  type: ClusterIP
  selector:
    app: broadcaster
  ports:
  - port: 2345
    protocol: TCP
    targetPort: 8500
