apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
data:
  init.sql: |
    CREATE DATABASE todos;
    CREATE TABLE todos(
      id VARCHAR(255) PRIMARY KEY,
      text VARCHAR(255),
      completed BOOLEAN,
      order_index INT
    );
