apiVersion: batch/v1
kind: CronJob
metadata:
  name: reminder
spec:
  schedule: 0 0 * * 0 # 38 * * * *  Changed to once per week so as to not flood the dicsord server
  jobTemplate:
    metadata:
      labels:
        job-name: reminder
    spec:
      template:
        spec:
          containers:
          - name: reminder
            image: djblackett/add-reminder:v0.4
            env:
            - name: API_URL
              value: http://todo-go-backend-svc:2345/todos
          restartPolicy: OnFailure
