apiVersion: ENC[AES256_GCM,data:aOg=,iv:Y52g65swMYXkXDV8fbJ/BTqYZTtkVXB/AteP5LuHWGw=,tag:xKfDVdhItDVEoBp8CX0NtA==,type:str]
kind: ENC[AES256_GCM,data:gYuesXoJ,iv:OT9aUxPsWT4t3HfsjWm+Ch0QQTBD7ha9InKZ+WrRIQo=,tag:YxG7TlsBGeNsaISX48E8cA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XmsM5FQcmlMRAl/VE/Ii45k=,iv:vQxZUgBDrxmG/GluxgPGQgPC/AV0e56W+QnYrq5NRKs=,tag:bP4QNSZZQEbP/Q+Z9tWJbg==,type:str]
data:
    PASSWORD: ENC[AES256_GCM,data:Iiy/viGpfsSi8gkG,iv:DqQvBu0TChvU1+ZOfFq5Eer8D67lShOZL5xISMCxD0g=,tag:fjnNdxkZvU8SbdSPFIFKng==,type:str]
#ENC[AES256_GCM,data:MQYsEqRqFUjVMXc+2UEXQwgmWkoqMKKdeb//Q4a/rbFkixSlIuxtAz0DuKnvC0ydcOLfW1U9FodcU9e/tSwaVed2zXMyU8OGSnzfiDaoE3E=,iv:iaXZoSuTPL1SvMXNtkEC9V0UmXNm8jGbLeaDhyXbPHw=,tag:klUjr0xUsMMhsgoV0FEIrQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age102209aw5afmtvadkfj2u0umzzq2g3ephhanc96qg686hl28089fspa6m23
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdlZOM1RzTWFNNFdac2VO
            L3ZRU2dvM1didUx5NDNjSy8zM1VWS2lGNGlZCmhWL1o4MEwvcENlMjBKSVBnY1kv
            UE1XZVlFMWpjM1MvZDFjZzl0Vk9SeUEKLS0tIHlDWHhZNGdjQWxXRkw4cDZxMmJN
            anFoY29Sd0pZZmQwSUFsK3RpcjViUnMKX7/JiNOXArNHtCFvr4XaK4Ot40n5Urb/
            TY6h/jkTBZ5+2tq14YMwmqINvVbqckwV06ItokwIvv3zR6FQVvjSqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-02T05:22:58Z"
    mac: ENC[AES256_GCM,data:MY1eO40wC2QDQzX/H9Xp1EX1W2zrcNojGqYDLEdzXSaMIbudp27kaaR3YVKgk78BFvD/xvKbSYoIU+kFUgvSlMPP0Mc7b4Gxgf5k2d93KAKFapxH/29GBnz2eLrIct4sbjilScnzwfEbx7fkY8lbfaE5JqPekOA8+U1TTNL7I+4=,iv:i4Q7jpY9nLX2GT5xUAzxpvWGUcCH8XkHDM7r4dt34Bo=,tag:t84CWg692x038IBYkaNZFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
