apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-go-frontend
spec:
  template:
    spec:
      containers:
      - name: todo-go-frontend
        image: djblackett/frontend:v4.02.8
