resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

# namePrefix: staging-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: backend
  newName: djblackett/backend
  newTag: bff1847189447aeef0860e844d1734afb4c694f3
- name: broadcaster
  newName: djblackett/broadcaster
  newTag: bff1847189447aeef0860e844d1734afb4c694f3
- name: frontend
  newName: djblackett/frontend
  newTag: bff1847189447aeef0860e844d1734afb4c694f3
namespace: staging
