resources:
- ../../base

patchesStrategicMerge:
- frontend.deployment.yaml
- backend.deployment.yaml
- broadcaster.deployment.yaml

namePrefix: staging-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: backend
  newName: djblackett/backend
  newTag: 9d23b0188ee646ed4bd6091e95519a27550fc447
- name: broadcaster
  newName: djblackett/broadcaster
  newTag: 9d23b0188ee646ed4bd6091e95519a27550fc447
- name: frontend
  newName: djblackett/frontend
  newTag: 9d23b0188ee646ed4bd6091e95519a27550fc447
namespace: staging
