resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

# namePrefix: staging-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: todo-go-backend
  newName: djblackett/todo-go-backend
  newTag: bff1847189447aeef0860e844d1734afb4c694f3
- name: todo-go-broadcaster
  newName: djblackett/todo-go-broadcaster
  newTag: bff1847189447aeef0860e844d1734afb4c694f3
- name: todo-go-frontend
  newName: djblackett/todo-go-frontend
  newTag: bff1847189447aeef0860e844d1734afb4c694f3
namespace: staging
