resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: eae0a756c38a058080fd93536472bbe385ba6639
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: eae0a756c38a058080fd93536472bbe385ba6639
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: eae0a756c38a058080fd93536472bbe385ba6639

namespace: staging
