resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: PROJECT/BACKEND
  newName: todo-go-backend
  newTag: a8e25dae48776f957fd82540a809d044d6b064ee
- name: PROJECT/BROADCASTER
  newName: todo-go-broadcaster
  newTag: a8e25dae48776f957fd82540a809d044d6b064ee
- name: PROJECT/FRONTEND
  newName: todo-go-frontend
  newTag: a8e25dae48776f957fd82540a809d044d6b064ee

namespace: staging
