resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: 142d4fccbfc850e2dbb284232e263877fa84dba2
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: 142d4fccbfc850e2dbb284232e263877fa84dba2
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: 142d4fccbfc850e2dbb284232e263877fa84dba2

namespace: staging
