resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: e9850f4fa00a74d54e914ea5a4ab6a909d75eece
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: e9850f4fa00a74d54e914ea5a4ab6a909d75eece
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: e9850f4fa00a74d54e914ea5a4ab6a909d75eece

namespace: staging
