resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

# namePrefix: staging-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: backend
  newName: djblackett/backend
  newTag: 62ff45eb3dc45b58f84c2bc45bf7bb32e0db455c
- name: broadcaster
  newName: djblackett/broadcaster
  newTag: 62ff45eb3dc45b58f84c2bc45bf7bb32e0db455c
- name: frontend
  newName: djblackett/frontend
  newTag: 62ff45eb3dc45b58f84c2bc45bf7bb32e0db455c
namespace: staging
