resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: daf01881edd96d4c343acedc7b653e9129f91a39
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: daf01881edd96d4c343acedc7b653e9129f91a39
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: daf01881edd96d4c343acedc7b653e9129f91a39

namespace: staging
