resources:
- ../../base

patchesStrategicMerge:
- broadcaster.deployment.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: PROJECT/BACKEND
  newName: djblackett/todo-go-backend
  newTag: df583e0a733917a747cac8c235d47e5b345cf3d8
- name: PROJECT/BROADCASTER
  newName: djblackett/todo-go-broadcaster
  newTag: df583e0a733917a747cac8c235d47e5b345cf3d8
- name: PROJECT/FRONTEND
  newName: djblackett/todo-go-frontend
  newTag: df583e0a733917a747cac8c235d47e5b345cf3d8

namespace: staging
