resources:
- ../../base
- persistentvolume.yaml
- persistentvolumeclaim.yaml

patchesStrategicMerge:
- broadcaster.deployment.yaml

# namePrefix: staging-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: todo-go-backend
  newName: djblackett/backend
  newTag: a8e25dae48776f957fd82540a809d044d6b064ee
- name: todo-go-broadcaster
  newName: djblackett/broadcaster
  newTag: a8e25dae48776f957fd82540a809d044d6b064ee
- name: todo-go-frontend
  newName: djblackett/frontend
  newTag: a8e25dae48776f957fd82540a809d044d6b064ee
namespace: staging
